SELECT 'DASH_ONTOLOGY', count(1) FROM DASH_ONTOLOGY
UNION
SELECT 'DASH_TAB_1_A', count(1) FROM DASH_TAB_1_A
UNION
SELECT 'DASH_TAB_1_B', count(1) FROM DASH_TAB_1_B
UNION
SELECT 'OBSERVATION_COUNT_TEMP', count(1) FROM OBSERVATION_COUNT_TEMP;