--SELECT C_HLEVEL,C_FULLNAME,ontology.CONCEPT_CD
--  FROM 
--  (SELECT * FROM 
--    (select C_HLEVEL,C_FULLNAME,C_NAME from UCLAMETADATA.UCLA WHERE C_HLEVEL<=4
--     UNION
--     select C_HLEVEL,C_FULLNAME,C_NAME from UCLAMETADATA.UCLA_DIAGS WHERE C_HLEVEL<=5
--     UNION
--     select C_HLEVEL,C_FULLNAME,C_NAME from UCLAMETADATA.UCLA_PROCS WHERE C_HLEVEL<=4
--     UNION
--     select C_HLEVEL,C_FULLNAME,C_NAME from UCLAMETADATA.UCLA LABS WHERE C_HLEVEL<=4 ) first
--     INNER JOIN uclacrcdata.CONCEPT_DIMENSION second
--     ON second.CONCEPT_PATH = first.C_FULLNAME
--     ORDER BY C_HLEVEL) ontology
--INNER JOIN i2b2data.OBSERVATION_FACT_COUNTS counts
--ON ontology.CONCEPT_CD = counts.CONCEPT_CD;

SELECT  C_HLEVEL,C_FULLNAME FROM (SELECT C_HLEVEL,C_FULLNAME FROM UCLAMETADATA.UCLA_DIAGS WHERE C_HLEVEL<=5) first
INNER JOIN
(SELECT  second.C_HLEVEL,second.C_FULLNAME FROM (SELECT C_HLEVEL,C_FULLNAME FROM UCLAMETADATA.UCLA_DIAGS WHERE C_HLEVEL=6) second) third
ON third.C_HLEVEL LIKE ('%' || first.C_HLEVEL || '%');
