--select ONTOLOGY_ID,ONTOLOGY_NAME,OBSERVATION_YEAR,OBSERVATION_COUNT from
select count(1) from
(select DASH_TAB_1_A.ONTOLOGY_ID as ontology_id,DASH_ONTOLOGY.C_FULLNAME as ontology_name from 
DASH_TAB_1_A
JOIN DASH_ONTOLOGY
ON DASH_TAB_1_A.ONTOLOGY_ID=DASH_ONTOLOGY.ID) first
--JOIN OBSERVATION_COUNT_TEMP
--ON first.ontology_name=OBSERVATION_COUNT_TEMP.C_DIMCODE;