SELECT C_FULLNAME FROM 
--SELECT count(1) FROM
DASH_ONTOLOGY INNER JOIN DASH_TAB_1_B
ON DASH_TAB_1_B.ID=DASH_ONTOLOGY.ID
WHERE C_HLEVEL<=5
GROUP BY DASH_ONTOLOGY.C_FULLNAME;
-------------------------
SELECT 'total rows ucla' as KEY,count(1) as count FROM DASH_UCLA
UNION
SELECT 'total rows uci' as KEY,count(1) as count FROM DASH_UCI
UNION
SELECT 'total rows ucsd' as KEY,count(1) as count FROM DASH_UCSD
UNION
SELECT 'Unique ontology elements UCLA' as KEY, count(1) as count FROM
  (SELECT DISTINCT C_DIMCODE FROM DASH_UCLA)
UNION
SELECT 'Unique ontology elements UCI' as KEY, count(1) as count FROM
  (SELECT DISTINCT C_DIMCODE FROM DASH_UCI)
UNION
SELECT 'Unique ontology elements UCSD' as KEY, count(1) as count FROM
  (SELECT DISTINCT C_DIMCODE FROM DASH_UCSD)
UNION
SELECT 'Overlapping ontology elements' as KEY, count(1) as count FROM
  (SELECT DISTINCT C_DIMCODE FROM DASH_ALL_SITES WHERE UCLA_COUNT!=0 AND UCI_COUNT!=0 AND UCSD_COUNT!=0)
UNION
SELECT 'Total ontology elements on dashboard' as KEY, count(1) as count FROM
  (SELECT DISTINCT C_FULLNAME FROM DASH_ONTOLOGY);
  
SELECT 'Year Range UCLA' as KEY, min(OBSERVATION_YEAR), max(OBSERVATION_YEAR) FROM DASH_UCLA WHERE OBSERVATION_YEAR!=9999
UNION
SELECT 'Year Range UCI' as KEY, min(OBSERVATION_YEAR), max(OBSERVATION_YEAR) FROM DASH_UCI WHERE OBSERVATION_YEAR!=9999
UNION
SELECT 'Year Range UCSD' as KEY, min(OBSERVATION_YEAR), max(OBSERVATION_YEAR) FROM DASH_UCSD WHERE OBSERVATION_YEAR!=9999;
-----------------------------------
SELECT C_FULLNAME FROM 
(SELECT tabap.PARENT_ID tabagp FROM 
(SELECT taba.PARENT_ID pid FROM
(SELECT DASH_ONTOLOGY.ID di  FROM 
--SELECT count(1) FROM
DASH_ONTOLOGY INNER JOIN DASH_TAB_1_B
ON DASH_TAB_1_B.ID=DASH_ONTOLOGY.ID
WHERE C_HLEVEL<=5
GROUP BY DASH_ONTOLOGY.ID) ids
INNER JOIN DASH_TAB_1_A taba
ON ids.di = taba.ontology_id
GROUP BY taba.PARENT_ID) parents
INNER JOIN DASH_TAB_1_A tabap
ON parents.pid=tabap.ONTOLOGY_ID
GROUP BY tabap.PARENT_ID) grandparents
INNER JOIN DASH_ONTOLOGY
ON DASH_ONTOLOGY.ID = grandparents.tabagp;
-----------------------------------

SELECT C_DIMCODE, count(C_DIMCODE) as count_years
FROM DASH_ALL_SITES
WHERE UCLA_COUNT > 0 AND UCI_COUNT > 0 AND UCSD_COUNT > 0
GROUP BY C_DIMCODE
HAVING count(C_DIMCODE) > 10
ORDER BY count_years desc
