INSERT INTO DASH_TAB_1_A 
SELECT ID ontology_id,0,C_NAME FROM DASH_ONTOLOGY 
WHERE C_HLEVEL=1;

INSERT INTO DASH_TAB_1_A 
SELECT second.ID ontology_id,first.ID parent_id,second.C_NAME FROM
(SELECT C_HLEVEL,C_FULLNAME,C_NAME,ID FROM DASH_ONTOLOGY WHERE C_HLEVEL=2)  first
JOIN
(SELECT C_HLEVEL,C_FULLNAME,C_NAME,ID FROM DASH_ONTOLOGY WHERE C_HLEVEL=3)   second
ON second.C_FULLNAME LIKE ('%' || first.C_FULLNAME || '%') ;