--create sequence dash_ont_seq start with 1 increment by 1 nomaxvalue; 
--
--UPDATE DASH_ONTOLOGY
--   SET id = dash_ont_seq.nextval;

--Below table names taken from TABLE_ACCESS
INSERT INTO DASH_ONTOLOGY SELECT C_HLEVEL, C_FULLNAME, C_NAME, DASH_ONT_SEQ.nextval FROM UCLA;
INSERT INTO DASH_ONTOLOGY SELECT C_HLEVEL, C_FULLNAME, C_NAME, DASH_ONT_SEQ.nextval FROM UCLA_DIAGS;
INSERT INTO DASH_ONTOLOGY SELECT C_HLEVEL, C_FULLNAME, C_NAME, DASH_ONT_SEQ.nextval FROM UCLA_PROCS;

--below yields 334549 records. C_HLEVEL goes from 1 through 10
SELECT COUNT(1) FROM DASH_ONTOLOGY;

SELECT C_HLEVEL,C_FULLNAME,C_NAME,ID FROM DASH_ONTOLOGY WHERE C_HLEVEL=1
